### ISSUE TITLE
[GAME BUG]: Blue Screen Filter during Gran Turismo 4 races

### ISSUE THREAD

**Issue by bibilu-alt** [ARMSX2/ARMSX2#96]
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.

### Game Title

Gran Turismo 4

### ARMSX2 Version

1.06

### Renderer (Graphics Backend)

Vulkan

### Device Model

Xiaomi Redmi Pad Pro 12.1

### OS Version

Android 14

### Describe the Bug

On default settings, the game runs normally up until the racing starts

Once the race starts on A-Mode, which is the one the player controls the car, there's a weird blue filter over the screen

### Reproduction Steps

1) Start the game

2)After creating a save file, open arcade mode, and select any race with any car

3)Start the race on the A-Spec, which is the driver's mode

Alternatively, you can start the race on the B-Spec, run up to the pit stop, switch to A-Spec mode there in the options, and the blue filter will still return

### Expected Behavior

There should not be any weird blue filter

**Comment by bibilu-alt** [comment]
The issue is actually on the modded version of Gran Turismo 4 Online Public Beta, named Gran Turismo 4 Spec II, running on the updated version 1.10

**Comment by rigui09rodri16-pixel** [comment]
I Fixed this by Pausing Mid-race, and went into Screen Settings. Made sure the brightness and contrast is set to 0. (This is how i fixed it)
(NOTE- RELFECTIONS AND TEXTURES MAY LOOK WEIRD)

**Comment by lipowskm** [comment]
Can confirm the issue still persists, thanks @rigui09rodri16-pixel for the fix, would be cool if we could change the screen settings ingame properly tho, instead of having to leave everything at 0.
